### ISSUE TITLE
Support for Thunderbird beta (64)

### ISSUE THREAD

**Issue by ToxicDragon** [emmanuelroecker/OpenGoogleCalendar#1]
Hi,

nice job in forking this wonderful add-on. However, could you please enable the support for installing in Thunderbird beta (currently at version 64), i.e. bumping the max version number up to 64.*? Would really need this :)

Cheers,
Christian

**Comment by emmanuelroecker** [comment]
Hi,

I'll look at it as soon as I can.

also :), you can write a review for this version on 
https://addons.thunderbird.net/en-US/thunderbird/addon/open-google-calendar/

Regards

**Comment by ToxicDragon** [comment]
Wow, that was quick 👍 :) Sure, will do once I'll have a Thunderbird 60 around ;)

In general I just investigated a bit; seems to be a pain in the a** to migrate from 60 to 64... They deactivated the old extension system. Bumped to number up myself and tried; did not work ("Non-restartless extensions no longer supported")... Guess the whole thing would be needed to be ported to web-extensions... See this extension for manipulating tabs as example: [https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs](https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs)

**Comment by ToxicDragon** [comment]
@emmanuelroecker Any progress so far?

**Comment by ToxicDragon** [comment]
@emmanuelroecker Any updates?

**Comment by emmanuelroecker** [comment]
Fixed and updated for Thunderbird 65 compatibility : https://addons.thunderbird.net/fr/thunderbird/addon/open-google-calendar/
